"vim generic settings
set number
set nocompatible
set backspace=indent,eol,start
set nowrap
set filetype=ps1
set ruler
set tabstop=4
set shiftwidth=4
set smartindent
set expandtab
set showtabline=0


"set directories
set nobackup "no backup file
set noswapfile "no swap file
set noundofile "no undo file



"remove text from NERDTree UI
let NERDTreeMinimalUI=1


"fix issues with colors in windows terminal
set termguicolors


"set default color scheme
colorscheme prusk


"syntax highlighting on
syntax on


"highlight line cursor is on
set cursorline



"set default shell
set shell=powershell\ -nologo
"set shell=pwsh\ -nologo


"shortcut to execute commands in terminal
noremap <C-;> Y<C-W>j<C-W>"0<C-W>k


"shortcut for scrolling in terminal (i to exit)
tnoremap <C-b> <C-\><C-n>


"shortcut for switching between code and terminal
noremap <C-/> <C-w>j
tnoremap <C-/> <C-w>k


"shortcut mapping ctrl+right to open new editor
noremap <C-Right> :vsplit new.ps1<CR>


"set aliases
cnoreabbrev powershell powershell -executionpolicy unrestricted -nologo
cabbrev bterm below term
cabbrev ntree NERDTree


"open terminal and NERDTree on start up and in new tabs
autocmd VimEnter * :below terminal
autocmd VimEnter * :NERDTree