"vim generic settings
set number
set nowrap
set filetype=ps1
set ruler
set smartindent "automatically set indents when writing code
set tabstop=4  "set number of spaces a tab is
set shiftwidth=4 "set number of spaces an indent is
set expandtab "tabs become spaces


"set directories
set nobackup "no backup file - used to recover file
set noswapfile "no swap file - used to avoid multiple edits to file and recover from crashes, merged when saving
set noundofile "no undo file - ability to roll back changes


"remove text from NERDTree UI
let NERDTreeMinimalUI=1


"fix issues with colors in windows terminal
set termguicolors


"set default color scheme
colorscheme prusk


"syntax highlighting on
syntax on


"highlight line cursor is on
set cursorline


"set default shell
set shell=powershell\ -nologo
"set shell=pwsh\ -nologo


"shortcut to execute commands in terminal
noremap <C-;> Y<C-W>j<C-W>"0<C-W>k


"shortcut for scrolling in terminal (i to exit)
tnoremap <C-b> <C-\><C-n>


"shortcut for switching between code and terminal
noremap <C-/> <C-w>j
tnoremap <C-/> <C-w>k


"shortcut mapping ctrl+right to open new editor
noremap <C-Right> :vsplit new.ps1<CR>


"set aliases
cnoreabbrev powershell powershell -executionpolicy unrestricted -nologo
cabbrev bterm below term
cabbrev ntree NERDTree


"open terminal and NERDTree on start up and in new tabs
autocmd VimEnter * :below terminal
autocmd VimEnter * :NERDTree